apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: application
  labels:
    app: employees
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: employees