apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: database
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 113222697619.dkr.ecr.us-east-1.amazonaws.com/clo835-database:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    ports:
    - containerPort: 3306